# 应用端口
server:
  port: 9003
# 应用名称
spring:
  application:
    name: gateway-dynamic-router-redis
  cloud:
    nacos:
      username: nacos
      password: nacos123
      server-addr: 123.60.148.210:8848
      discovery:
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        namespace: 1e3e5606-e4b6-4935-9c57-a44e34a6e770
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        namespace: 1e3e5606-e4b6-4935-9c57-a44e34a6e770
        server-addr: ${spring.cloud.nacos.server-addr}

  redis:
    host: 123.60.148.210
    port: 6379
    database: 0
    password: redis123
    lettuce:
      pool:
        enabled: true
# http://{ip}:{port}/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans





