# 应用端口
server:
  port: 9002
# 应用名称
spring:
  application:
    name: gateway-dynamic-router-nacos
  cloud:
    nacos:
      username: nacos
      password: nacos123
      server-addr: 123.60.148.210:8848
      discovery:
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        namespace: 1e3e5606-e4b6-4935-9c57-a44e34a6e770
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        namespace: 1e3e5606-e4b6-4935-9c57-a44e34a6e770
        server-addr: ${spring.cloud.nacos.server-addr}

nacos:
  gateway:
    route:
      config:
        data-id: nacos-gateway
        group: DEFAULT_GROUP


# http://{ip}:{port}/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans


